### ISSUE TITLE
general lecture

### ISSUE THREAD

**Issue by Sinonaif** [zuri-training/Favicon_gen-Team-68#128]
organised series of lectures for both developers and designers.

**Comment by Sinonaif** [comment]
Gave a talk on primary, secondary and tertiary buttons and the benefits of implementing a 4 point system in a designs amongst other topics

**Comment by joanamadasun** [comment]
I explained what a primary, secondary and tertiary button is and where and how they can be used in design. I explained button material design, shape psychology and colour psychology in design to team members with @Adevikthur . 

I helped members understand how to implement a spacing system in their designs by creating a figures template designers could use. I explained how also using our grid system I created would make things easier because it already follows our spacing system

**Comment by Conradgabe** [comment]
I organised brief meetings to teach, explain and provided materials to the developer team members
